# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI - Verify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Maven Compile
      run: mvn -B clean compile
    - name: Docker Login
      run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    - name: Run Kafka Docker
      run: docker run -d -p 2181:2181 -p 9092:9092 ghcr.io/discoverivan/kafka:latest
    - name: Maven Test
      run: mvn -B clean verify
